name: Automatic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Zip File
        run: zip -r fcup-latex-template $GITHUB_WORKSPACE -x .git/* -x .github/*

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Fcup Latex Template"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          body: |
            Changes in this release:
            - Describe your changes here
          prerelease: false
          files: fcup-latex-template.zip
