name: Automatic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Create Zip File
        run: cd $GITHUB_WORKSPACE && zip -r fcup-latex-template.zip . -x ./.git/* -x ./.github/*

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Fcup Latex Template"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: fcup-latex-template.zip
